language: go
go:
  - 1.6
install:
  - echo "skipping install step"
env:
  - TEST_DIR=worker/acmebot
  - TEST_DIR=worker/acmebot-k8s
  - TEST_DIR=worker/deploybot
  - TEST_DIR=worker/deploybot-k8s
script:
  - cd $TEST_DIR && ./travis.sh