language: go
go:
  - 1.6
install:
  - echo "skipping install step"
env:
  - TEST_DIR=acmebot
  - TEST_DIR=acmebot-k8s
  - TEST_DIR=deploybot
  - TEST_DIR=deploybot-k8s
script:
  - cd $TEST_DIR && ./travis.sh